### ISSUE TITLE
Feature request: Enter key act as "Carriage Return" 

### ISSUE THREAD

**Issue by Shahdoh** [ThroughlyDruxy/tor2e-npc-parser#11]
To facilitate editing in the working area of the input area. It would be great if "Enter" only worked as a "Carriage Return". At the moment, it functions the same as clicking on "GO" and processes the entered information.

Sometimes, due to inconsistencies of provided data from either official or unofficial source materials, these manual edits by the user become necessary for a successful import.

Thank you for your consideration on the matter.

**Comment by ThroughlyDruxy** [comment]
Added. See latest release
