### ISSUE TITLE
FVTT 11 - Module validation error during update

### ISSUE THREAD

**Issue by r-valyar** [ThroughlyDruxy/tor2e-npc-parser#16]
The following error occurs when update module is performed in FVTT v11:

![image](https://github.com/ThroughlyDruxy/tor2e-npc-parser/assets/63558984/865cbaa9-0b24-4e18-b7c3-cd258649cadb)

**Comment by ThroughlyDruxy** [comment]
I'll check it out. But I also haven't verified with with V11 so that may be
the issue.
