### ISSUE TITLE
Will this be updated for FVTT v12 compatibility?

### ISSUE THREAD

**Issue by abandonedbrain** [ThroughlyDruxy/tor2e-npc-parser#18]
I just started using FoundryVTT this week, and as such installed v12 as the site offers it as "stable". Now that I've started adding a few systems, I've been directed to NPC Parser as an add-on module for use with TOR 2e (using for solo gaming). Will this module be updated for v12?

_Error: [undefinded] module tor2e-npc-parser version 0.5.5 requires an older version of the Foundry Virtual Tabletop software: 11 or older_

**Comment by ThroughlyDruxy** [comment]
I don't have specific plans too as I've been busy with other stuff. But I can take a look soonish and see what it would look like to get it updated for v12. Also feel free to ping me in the TOR discord or DM me on discord. Additionally there are compendiums for the adversaries that just don't include some of the text and are probably less difficult to deal with than my module.

**Comment by abandonedbrain** [comment]
Thanks, you did not have to reply that quickly!

**Comment by ThroughlyDruxy** [comment]
And updated! May take a bit to populate that an update is available but version 0.6.0 of the parser should be working with Foundry V12. Please let me know if you have any issues.
